### ISSUE TITLE
Cannot make this action work

### ISSUE THREAD

**Issue by imgalli** [nwisbeta/validate-yaml-schema#17]
Hi, I've previously used this action with identical settings to validate the GitHub workflow files but now when trying to do the same in another repo it fails.

<img width="1069" alt="Screenshot 2021-07-07 at 09 36 01" src="https://user-images.githubusercontent.com/75438384/124727583-c43c0e00-df06-11eb-8fbc-89570ef6d149.png">

This is with the following workflow:
```
name: validate-workflows
on:
  pull_request:
    paths:
      - ".github/workflows/**"
jobs:
  validate_workflows:
    name: Validate GH workflows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - self-hosted-ubuntu-2004
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Validate GH Workflows
        uses: nwisbeta/validate-yaml-schema@v1.0.3
```

And `.vscode/settings.json`
```
{
  "yaml.schemas": {
    "https://json.schemastore.org/github-workflow.json": [
      ".github/workflows/*.yml"
    ]
  },
}
```
